title: Roman Kovtun Portfolio
logo: Roman Kovtun
email: gyto23@gmail.com
description: >
  Roman Kovtun is Front End Developer with experience more that 3 years. He inspire to build website quick and fast.
baseurl: "/portfolio"
url: "https://gyto.github.io"
twitter_username: gyto23
github_username:  gyto

# Build settings
#markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
